### obtener todos los categorias productos

GET http://localhost:2500/api/categoriasProductos

### obtener una categoria producto
GET http://localhost:2500/api/categoriasProductos/1

### crear una categoria producto
POST http://localhost:2500/api/categoriasProductos
Content-Type: application/json

{ "nombre": "entradas -2" }

### actualizar una categoria producto
PUT http://localhost:2500/api/categoriasProductos/1
Content-Type: application/json

{ "nombre": "entradas" }

### eliminar una categoria producto
DELETE http://localhost:2500/api/categoriasProductos/2