### obtener todos los productos

GET http://localhost:2500/api/productos

### obtener un producto
GET http://localhost:2500/api/productos/1

### obtener todos los pedidos que tengan relacion con sus categorias
GET http://localhost:2500/api/productosConCategorias/17

### crear un producto
POST http://localhost:2500/api/productos
Content-Type: application/json

{
  "nombre": "otra comida | otra categoria",
  "precio": 20000,
  "stock": 15,
  "icono": "*falta rellenar*",
  "imagen": "*falta rellenar*",
  "id_categoria_producto": 2
}

### actualizar un producto
PUT http://localhost:2500/api/productos/1
Content-Type: application/json

{
  "nombre": "hamburguesa-testing [editado]",
  "precio": 15000,
  "stock": 200,
  "icono": "*falta rellenar*",
  "imagen": "*falta rellenar*",
  "id_categoria_producto": 1
}

### eliminar un producto
DELETE http://localhost:2500/api/productos/4